### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ingvarr71** [JDCTeam/manifests#3]
Hello!
What are these errors?

[ 76% 86596/113019] target  C++: hwcomposer.sdm660 <= hardware/qcom-caf/msm8998/display/sdm/libs/hwc2/hwc_session_services.cpp
FAILED: out/target/product/tulip/obj/SHARED_LIBRARIES/hwcomposer.sdm660_intermediates/hwc_session_services.o
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang++ 	-I system/core/base/include -I hardware/qcom-caf/msm8998/display/sdm/libs/hwc2 -I out/target/product/tulip/obj/SHARED_LIBRARIES/hwcomposer.sdm660_intermediates -I out/target/product/tulip/gen/SHARED_LIBRARIES/hwcomposer.sdm660_intermediates \$(cat out/target/product/tulip/obj/SHARED_LIBRARIES/hwcomposer.sdm660_intermediates/import_includes)   -isystem out/target/product/tulip/obj/include -c  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a -mcpu=kryo -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin  -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++17   -fno-rtti -Wno-missing-field-initializers -Wno-unused-parameter -std=c++11 -fcolor-diagnostics -DLOG_TAG=\\\"SDM\\\" -DDEBUG_CALC_FPS -Wno-missing-field-initializers -Wconversion -Wall -Werror -std=c++14 -DDISPLAY_CONFIG_1_1 -DDISPLAY_CONFIG_1_2 -DDISPLAY_CONFIG_1_3 -DDISPLAY_CONFIG_1_4 -DDISPLAY_CONFIG_1_5 -DDISPLAY_CONFIG_1_6 -DDISPLAY_CONFIG_1_7 -DDISPLAY_CONFIG_1_8 -DDISPLAY_CONFIG_1_9 -DUSE_COLOR_METADATA -D__ARM_HAVE_NEON -DMASTER_SIDE_CP -DVIDEO_MODE_DEFER_RETIRE_FENCE -DUSE_GRALLOC1 -I hardware/qcom-caf/msm8998/display/sdm/libs/hwc2/../../../sdm/libs/hwc -D__ANDROID_API__=29 -D__ANDROID_VNDK__ -fPIC -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11  -MD -MF out/target/product/tulip/obj/SHARED_LIBRARIES/hwcomposer.sdm660_intermediates/hwc_session_services.d -o out/target/product/tulip/obj/SHARED_LIBRARIES/hwcomposer.sdm660_intermediates/hwc_session_services.o hardware/qcom-caf/msm8998/display/sdm/libs/hwc2/hwc_session_services.cpp"
hardware/qcom-caf/msm8998/display/sdm/libs/hwc2/hwc_session_services.cpp:626:44: error: use of undeclared identifier 'HWC_DISPLAY_BUILTIN_2'; did you mean 'HWC_DISPLAY_WIDTH'?
  if ((HWC_DISPLAY_PRIMARY == disp_id) || (HWC_DISPLAY_BUILTIN_2 == disp_id) ||
                                           ^~~~~~~~~~~~~~~~~~~~~
                                           HWC_DISPLAY_WIDTH
hardware/libhardware/include/hardware/hwcomposer_defs.h:236:5: note: 'HWC_DISPLAY_WIDTH' declared here
    HWC_DISPLAY_WIDTH                       = 2,
    ^
hardware/qcom-caf/msm8998/display/sdm/libs/hwc2/hwc_session_services.cpp:627:8: error: use of undeclared identifier 'HWC_DISPLAY_BUILTIN_3'; did you mean 'HWC_DISPLAY_WIDTH'?
      (HWC_DISPLAY_BUILTIN_3 == disp_id) || (HWC_DISPLAY_BUILTIN_4 == disp_id)) {
       ^~~~~~~~~~~~~~~~~~~~~
       HWC_DISPLAY_WIDTH
hardware/libhardware/include/hardware/hwcomposer_defs.h:236:5: note: 'HWC_DISPLAY_WIDTH' declared here
    HWC_DISPLAY_WIDTH                       = 2,
    ^
hardware/qcom-caf/msm8998/display/sdm/libs/hwc2/hwc_session_services.cpp:627:46: error: use of undeclared identifier 'HWC_DISPLAY_BUILTIN_4'
      (HWC_DISPLAY_BUILTIN_3 == disp_id) || (HWC_DISPLAY_BUILTIN_4 == disp_id)) {
                                             ^
3 errors generated.
13:52:27 ninja failed with: exit status 1

**Comment by Buff99** [comment]
what are you trying to build?

**Comment by dkati** [comment]
keep in mind that some repos outside 8960 may be missing. we build for jf (msm8960).

although i want to help u port optlos to your non-jf device. as buff asked....what are you trying to build?

**Comment by Ingvarr71** [comment]
> what are you trying to build?



> keep in mind that some repos outside 8960 may be missing. we build for jf (msm8960).
> 
> although i want to help u port optlos to your non-jf device. as buff asked....what are you trying to build?

firmware for Xiaomi Redmi Note 6 Pro

**Comment by dkati** [comment]
please try to use lineage manifest's HAL
